#!/usr/bin/env bash

install_dotfiles()
{
  local files=(   \
    .bash_aliases \
    .bash_profile \
    .bashrc       \
    .bin          \
    .gitconfig    \
    .gitignore    \
    .irbrc        \
    .motd         \
    .nanorc       \
    .pythonrc     \
  )

  local path="$PWD"
  local install_path="$HOME"

  [[ -n "$1" ]] && install_path="$1"

  for file in ${files[@]}; do
    echo "Installing $file"
    rm -rf "$install_path/$file"
    ln -s "$path/$file" "$install_path/$file"
  done

}

install_dotfiles "$@"
