#!/usr/bin/env bash

install_dotfiles()
{
  local files=(     \
    .bashrc         \
    .bash_functions \
    .bash_profile   \
    .bash_aliases   \
    .gitconfig      \
    .gitignore      \
    .nanorc         \
    .irbrc          \
    .pythonrc       \
    .motd           \
    .bin            \
  )

  local path="$PWD"
  local install_path="$HOME"

  [[ -n "$1" ]] && install_path="$1"

  echo "Installing dotfiles. Hang tight!"

  for file in ${files[@]}; do
    rm -rf "$install_path/$file"
    ln -s "$path/$file" "$install_path/$file"
    echo "  $file"
  done

  echo "Completed!"
}

install_dotfiles "$@"
