#!/usr/bin/env bash

# Enable Backspace/Delete key in Safari
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool YES

# Make OS X screenshots without window shadows
defaults write com.apple.screencapture disable-shadow -bool true

# Removing the date and time Stamp from Screenshots
defaults write com.apple.screencapture include-date -bool false

# Change Notification Center's banner display time
defaults write com.apple.notificationcenterui bannerTime 3

# Disable TextEdit's Ruler
defaults write com.apple.TextEdit ShowRuler 0

# Use plain text as default format in TextEdit
defaults write com.apple.TextEdit RichText 0

# Open a new file in TextEdit on launch
defaults write -g NSShowAppCentricOpenPanelInsteadOfUntitledFile -bool false

# Disable warning when changing file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Enable the expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Make Crash Reporter appear as a notification
defaults write com.apple.CrashReporter UseUNC 1

# Disable the pop-up accent menu when typing
defaults write -g ApplePressAndHoldEnabled -bool false

killall Finder
killall SystemUIServer

echo "Finder and SystemUIServer were killed for some of the settings to take effect!"
